# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='title_slug',
            new_name='slug_title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_slug',
            new_name='slug_title',
        ),
    ]
