# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170120_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='post_type',
            field=models.CharField(choices=[('N', 'Publicación'), ('A', 'Audio'), ('L', 'Libro'), ('C', 'Conferencia')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('N', 'Publicación'), ('A', 'Audio'), ('L', 'Libro'), ('C', 'Conferencia')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug_name',
            field=models.SlugField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='slug_title',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug_title',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug_name',
            field=models.SlugField(blank=True, max_length=90, null=True),
        ),
    ]
