# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 07:39
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170124_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
